const seed=[
['richard','Richard Blahut','Primary Owner','owner','','Primary owner of Williams Cottage Inn.'],
['jan','Jan Blahut','Family Ownership','family','Richard’s daughter · Mike’s wife',''],
['mike','Mike Ryan','Family Ownership','family','Jan’s husband',''],
['greg','Greg Blahut','Family Ownership','family','Richard’s son · Jan and Ken’s brother',''],
['ken','Ken Blahut','Family Ownership','family','Richard’s son · Jan and Greg’s brother',''],
['justine','Justine','Director of Inn Experience & Operations','leadership','','Inn oversight, guest relations, reservations, communications, marketing, and service coordination.'],
['don','Don Blahut','General Manager','leadership','Richard’s nephew · Jim’s brother','Home maintenance, excluding vendor-related maintenance.'],
['jim','Jim Blahut','Family Support · Perennial Homes','support','Don’s brother','Perennial Homes — crew available to support renovations. Jim also contributed the initial door repair.'],
['sharon','Sharon Blahut','Serving Support','support','Michael’s wife','Occasional help with serving.'],
['michael','Michael Blahut','Landscaper','support','Sharon’s husband','Landscaping.'],
['colleen','Colleen','Cleaning','support','','Last name to be confirmed.'],
['amancia','Amancia Cleaning Service','Cleaning Service','support','','Service contact to be added.'],
['betsy','Betsy Muñoz','Chef / Cooking Support','support','','Available as a potential chef; arrangements to be confirmed.'],
['christine','Christine','Personal Support / Champion','champions','','Owner of Dockside Diner. Last name to be confirmed.'],
['jeannie','Jeannie Gasparelli','Shoulder-season Support','justineTeam','','Surname is provisional. Shoulder-season support.'],
['rami','Rami','Winter Support (November–March)','support','','Winter support, November–March, with her husband. Last name to be confirmed.'],
['ramipartner','Rami’s husband','Winter Support (November–March)','support','Rami’s husband','November–March support with Rami. Name and responsibilities to be confirmed.']
,['laurence','Laurence Heating & Air Conditioning','HVAC Service','support','','Serves Long Beach Island and Southern Ocean County. Likely match for “Lawrence”; contractor identity to be confirmed.'],
['eric','Eric Brummer','Plumber · Brummer the Plumber','support','','Brummer the Plumber, Manahawkin, NJ.']
].map(([id,name,role,group,relation,notes])=>({id,name,role,group,relation,notes,phone:'',email:'',reports:group==='leadership'?'Family ownership; Justine and Don work as partners':''}));
const contactUpdates={sharon:{phone:'201-988-4625'},mike:{phone:'571-606-2461'},laurence:{phone:'609-703-4950',email:'laurenceheatair@gmail.com'},eric:{phone:'609-597-4895',email:'brummertheplumber@comcast.net'}};
seed.forEach(p=>Object.assign(p,contactUpdates[p.id]||{}));
function migrateContacts(saved){const result=saved.map(p=>({...p}));for(const id of ['sharon','mike','jim']){const p=result.find(p=>p.id===id),fresh=seed.find(p=>p.id===id);if(p){if(id==='jim'){p.role=fresh.role;p.notes=fresh.notes}else Object.assign(p,contactUpdates[id])}}for(const id of ['laurence','eric'])if(!result.some(p=>p.id===id))result.push({...seed.find(p=>p.id===id)});return result}
for(const id of ['jeannie','christine'])seed.find(p=>p.id===id).reports='Justine';
function migrateBranches(saved){return saved.map(p=>{const fresh=seed.find(x=>x.id===p.id);if(['christine','jeannie'].includes(p.id))return {...p,role:fresh.role,group:fresh.group,reports:'Justine'};if(['rami','ramipartner'].includes(p.id))return {...p,role:fresh.role,notes:fresh.notes};return {...p}})}
const familyPhoneUpdates={richard:{phone:'610-241-4206'},justine:{name:'Justine',phone:'609-492-7272'},jim:{phone:'609-709-9019'},jan:{phone:'703-303-1947'},deborah:{name:'Deborah Blahut',phone:'215-870-8910'}};
seed.forEach(p=>Object.assign(p,familyPhoneUpdates[p.id]||{}));
function migrateFamilyPhones(saved){return saved.map(p=>{const updated={...p,...(familyPhoneUpdates[p.id]||{})};if(p.id==='deborah'&&p.notes==='Last name to be confirmed.')updated.notes='';return updated})}
const rickEntry={id:'rick',name:'Rick',role:'Jim’s Team',group:'jimTeam',relation:'',notes:'Last name and specific responsibilities to be confirmed.',phone:'609-618-2530',email:'',reports:'Jim Blahut'};
seed.push(rickEntry);
function migrateRick(saved){return saved.some(p=>p.id==='rick')?saved:[...saved,{...rickEntry}]}
const latestContactUpdates={greg:{phone:'843-505-2537'},ken:{phone:'609-338-7276'}};
seed.forEach(p=>Object.assign(p,latestContactUpdates[p.id]||{}));
const robinEntry={id:'robin',name:'Robin MacMillan',role:'Professional Support · Role to Confirm',group:'support',relation:'',notes:'',phone:'',email:'CPA-LRM@comcast.net',reports:''};
seed.push(robinEntry);
function migrateRobinContacts(saved){const updated=saved.map(p=>({...p,...(latestContactUpdates[p.id]||{})}));if(!updated.some(p=>p.id==='robin'))updated.push({...robinEntry});return updated}
const summerStaff=[{id:'kristina',name:'Kristina Blahutova'},{id:'natalia',name:'Natalia Javorova'}].map(p=>({...p,role:'Summer Cleaning & Cooking',group:'support',relation:'',notes:'Late June through the end of August.',phone:'',email:'',reports:'Justine'}));
seed.push(...summerStaff);
function migrateSeasons(saved){const next=saved.map(p=>({...p}));for(const person of summerStaff)if(!next.some(p=>p.id===person.id))next.push({...person});for(const p of next){if(['colleen','betsy','amancia'].includes(p.id)&&!p.notes.includes('September'))p.notes+=' Availability: September through mid-June.';if(['rami','ramipartner'].includes(p.id)){p.role='Winter Support · Nov 1–Mar 31';p.notes=p.id==='rami'?'November 1 through March 31, with her husband. Last name to be confirmed.':'November 1 through March 31, with Rami. Name and specific responsibilities to be confirmed.';}}return next}
const key='williams-empire-roster-v1',groups=['owner','family','leadership','support','justineTeam','champions','jimTeam'];let roster=seed,editing=null;const $=s=>document.querySelector(s);function valid(v){return Array.isArray(v)&&v.length<=300&&v.every(p=>p&&typeof p.id==='string'&&typeof p.name==='string'&&typeof p.role==='string'&&groups.includes(p.group)&&['relation','notes','phone','email','reports'].every(k=>typeof p[k]==='string'))&&new Set(v.map(p=>p.id)).size===v.length}try{const saved=JSON.parse(localStorage.getItem(key));if(valid(saved)){roster=saved;if(localStorage.getItem(key+'-contacts-20260924')!=='applied'){roster=migrateContacts(saved);localStorage.setItem(key,JSON.stringify(roster));localStorage.setItem(key+'-contacts-20260924','applied')}}else if(saved===null){localStorage.setItem(key+'-contacts-20260924','applied')}}catch{}try{if(localStorage.getItem(key+'-branches-v1')!=='applied'){roster=migrateBranches(roster);localStorage.setItem(key,JSON.stringify(roster));localStorage.setItem(key+'-branches-v1','applied')}}catch{roster=migrateBranches(roster)}
try{if(localStorage.getItem(key+'-family-phones-v1')!=='applied'){roster=migrateFamilyPhones(roster);localStorage.setItem(key,JSON.stringify(roster));localStorage.setItem(key+'-family-phones-v1','applied')}}catch{roster=migrateFamilyPhones(roster)}
try{if(localStorage.getItem(key+'-rick-v1')!=='applied'){roster=migrateRick(roster);localStorage.setItem(key,JSON.stringify(roster));localStorage.setItem(key+'-rick-v1','applied')}}catch{roster=migrateRick(roster)}
try{if(localStorage.getItem(key+'-robin-contacts-v1')!=='applied'){roster=migrateRobinContacts(roster);localStorage.setItem(key,JSON.stringify(roster));localStorage.setItem(key+'-robin-contacts-v1','applied')}}catch{roster=migrateRobinContacts(roster)}
try{if(localStorage.getItem(key+'-seasons-v1')!=='applied'){roster=migrateSeasons(roster);localStorage.setItem(key,JSON.stringify(roster));localStorage.setItem(key+'-seasons-v1','applied')}}catch{roster=migrateSeasons(roster)}
const seasonViews={shoulder:{title:'Shoulder-season support',dates:'April–May · September–October',people:['jeannie','colleen','amancia','heather','betsy','flavia','christine'],description:''},summer:{title:'Summer support',dates:'Late June–end of August',people:['kristina','natalia','amancia'],description:''},winter:{title:'Winter support',dates:'November 1–March 31',people:['rami','ramipartner','colleen','amancia','heather','betsy','flavia','christine'],description:''},directory:{title:'Complete support directory',dates:'All seasons · all contacts',people:null,description:''}};
let activeView=Object.hasOwn(seasonViews,location.hash.slice(1))?location.hash.slice(1):'shoulder';
function seasonRoster(){const selected=seasonViews[activeView];return selected.people?roster.filter(p=>['owner','family','leadership'].includes(p.group)||['jim','sharon','michael','rick','mike'].includes(p.id)||(activeView==='shoulder'&&p.id==='host-backup')||selected.people.includes(p.id)):roster}
function updateView(){const v=seasonViews[activeView];$('#season-title').textContent=v.title;$('#season-dates').textContent=v.dates;$('#season-description').textContent=v.description;document.querySelectorAll('[data-season]').forEach(a=>{a.setAttribute('aria-current',a.dataset.season===activeView?'page':'false')});$('.open-roles').hidden=activeView!=='directory';render()}
window.addEventListener('hashchange',()=>{if(Object.hasOwn(seasonViews,location.hash.slice(1))){activeView=location.hash.slice(1);updateView()}});
function updateReporting(items){return items.map(p=>{if(['jim','sharon','michael'].includes(p.id))return {...p,reports:'Don Blahut'};if(p.id==='rick'||p.group==='jimTeam')return {...p,reports:'Jim Blahut'};if(['support','justineTeam','champions'].includes(p.group))return {...p,reports:'Justine'};return p})}
try{if(localStorage.getItem(key+'-reporting-v1')!=='applied'){roster=updateReporting(roster);localStorage.setItem(key,JSON.stringify(roster));localStorage.setItem(key+'-reporting-v1','applied')}}catch{roster=updateReporting(roster)}
function migrateCategories(items){const next=items.map(p=>({...p}));for(const [id,name,role,notes] of [['heather','Heather','Cleaning','Last name and contact details to be confirmed. September through mid-June.'],['flavia',"Flavia’s Kitchen",'Chef · Flavia Katz','September through mid-June. Contact details to be confirmed.']])if(!next.some(p=>p.id===id))next.push({id,name,role,notes,group:'support',relation:'',phone:'',email:'',reports:'Justine'});for(const p of next){if(p.id==='betsy'){p.name='Beez Eats';p.role='Chef · Betsy Muñoz'}if(p.id==='jeannie'){p.role='On-Site Host · Shoulder Season';p.notes='September, October, April, and May. Surname is provisional.'}if(['rami','ramipartner'].includes(p.id))p.role='On-Site Host · Winter';if(p.id==='christine')p.role='Champion';}return next}
try{if(localStorage.getItem(key+'-categories-v1')!=='applied'){roster=migrateCategories(roster);localStorage.setItem(key,JSON.stringify(roster));localStorage.setItem(key+'-categories-v1','applied')}}catch{roster=migrateCategories(roster)}
function refineRoster(items){return items.map(p=>{const q={...p};for(const k of ['name','relation','reports','notes'])q[k]=q[k].replaceAll('Blayhut','Blahut');q.notes=q.notes.replace(/Last name and contact details to be confirmed\.?/gi,'').trim();if(q.id==='justine'&&!q.notes.includes('Digital Ambassador'))q.notes='Digital Ambassador. '+q.notes;if(q.id==='betsy')q.name='Betsy Muñoz';if(q.id==='flavia')q.name='Flavia Katz';if(['heather','amancia'].includes(q.id))q.role='Emergency Backup · Cleaning';return q})}
try{if(localStorage.getItem(key+'-org-layout-v1')!=='applied'){roster=refineRoster(roster);localStorage.setItem(key,JSON.stringify(roster));localStorage.setItem(key+'-org-layout-v1','applied')}}catch{roster=refineRoster(roster)}
function migrateSharedTeam(items){return items.filter(p=>p.id!=='deborah').map(p=>{if(p.id==='jim')return {...p,reports:'Don Blahut'};if(p.id==='michael')return {...p,name:'Mike Blahut',role:'Landscaping',reports:'Don Blahut'};if(p.id==='sharon')return {...p,role:'Serving · Shared Contact',reports:'Justine & Don Blahut',relation:'',notes:'Occasional serving support.'};return p})}
try{if(localStorage.getItem(key+'-shared-serving-v1')!=='applied'){roster=migrateSharedTeam(roster);localStorage.setItem(key,JSON.stringify(roster));localStorage.setItem(key+'-shared-serving-v1','applied')}}catch{roster=migrateSharedTeam(roster)}
function migrateHostBackup(items){const next=items.map(p=>p.id==='kristina'?{...p,name:'Kristina Blahutova'}:p);if(!next.some(p=>p.id==='host-backup'))next.push({id:'host-backup',name:'Melissa & Ben',role:'Emergency Backup · On-Site Host',group:'support',relation:'',notes:'',phone:'',email:'',reports:'Justine'});return next}
try{if(localStorage.getItem(key+'-host-backup-v1')!=='applied'){roster=migrateHostBackup(roster);localStorage.setItem(key,JSON.stringify(roster));localStorage.setItem(key+'-host-backup-v1','applied')}}catch{roster=migrateHostBackup(roster)}
function migrateSummerBackups(items){return items.map(p=>{if(p.id==='jim')return {...p,role:'Renovations',notes:''};if(p.id==='rick')return {...p,role:'Perennial Homes',notes:''};if(p.id==='sharon')return {...p,role:'Serving',reports:'Don Blahut',notes:''};if(p.id==='michael')return {...p,role:'Landscaping',notes:''};return p})}
try{if(localStorage.getItem(key+'-summer-backups-v1')!=='applied'){roster=migrateSummerBackups(roster);localStorage.setItem(key,JSON.stringify(roster));localStorage.setItem(key+'-summer-backups-v1','applied')}}catch{roster=migrateSummerBackups(roster)}
function migrateFamilyRow(items){return items.filter(p=>p.id!=='judy').map(p=>p.id==='justine'?{...p,notes:'Digital Ambassador, partnerships, and on-site expert. Inn oversight, guest relations, reservations, communications, marketing, and service coordination.'}:p)}
try{if(localStorage.getItem(key+'-family-row-v1')!=='applied'){roster=migrateFamilyRow(roster);localStorage.setItem(key,JSON.stringify(roster));localStorage.setItem(key+'-family-row-v1','applied')}}catch{roster=migrateFamilyRow(roster)}
function migrateCompactTeam(items){return items.filter(p=>p.id!=='christine').map(p=>{if(p.id==='rick')return {...p,role:'Handyman',notes:''};if(p.id==='mike')return {...p,group:'support',role:'On-Site Host / Serving / Maintenance',relation:'',notes:'',reports:'Don Blahut'};return p})}
try{if(localStorage.getItem(key+'-compact-team-v1')!=='applied'){roster=migrateCompactTeam(roster);localStorage.setItem(key,JSON.stringify(roster));localStorage.setItem(key+'-compact-team-v1','applied')}}catch{roster=migrateCompactTeam(roster)}
function migrateBrandLeadership(items){return items.map(p=>p.id==='justine'?{...p,notes:"The face of Williams Cottage Inn and steward of its brand and guest experience. Leads year-round operations, guest relations, reservations, website and social media, partnerships, staff coordination, and communication. Oversees meal planning, purchasing, inventory, and culinary coordination. On-site expert, identifying property needs, prioritizing improvements, and coordinating solutions."}:p.id==='richard'?{...p,name:'Richard Blahut',role:'Owner',notes:''}:p)}
try{if(localStorage.getItem(key+'-brand-leadership-v1')!=='applied'){roster=migrateBrandLeadership(roster);localStorage.setItem(key,JSON.stringify(roster));localStorage.setItem(key+'-brand-leadership-v1','applied')}}catch{roster=migrateBrandLeadership(roster)}
function trimContactDescriptions(items){return items.map(p=>p.id==='justine'?{...p,notes:p.notes.replace(' across the ownership family','').replace('Serves as summer host and on-site expert,','On-site expert,').replace('coordinating solutions with Don.','coordinating solutions.')}:p.id==='robin'?{...p,notes:''}:p)}
try{if(localStorage.getItem(key+'-trim-descriptions-v1')!=='applied'){roster=trimContactDescriptions(roster);localStorage.setItem(key,JSON.stringify(roster));localStorage.setItem(key+'-trim-descriptions-v1','applied')}}catch{roster=trimContactDescriptions(roster)}
function updateVendorDetails(items){return items.map(p=>p.id==='laurence'?{...p,phone:'609-703-4950',email:'',notes:p.notes.replace(/Likely match.*confirmed\./i,'').trim()}:p.id==='eric'?{...p,role:'Plumber',phone:'609-597-4895',email:'',notes:''}:p)}
try{if(localStorage.getItem(key+'-vendor-details-v2')!=='applied'){roster=updateVendorDetails(roster);localStorage.setItem(key,JSON.stringify(roster));localStorage.setItem(key+'-vendor-details-v2','applied')}}catch{roster=updateVendorDetails(roster)}
function updateDonResponsibilities(items){return items.map(p=>p.id==='don'?{...p,notes:"Leads property maintenance and readiness, ensuring outstanding jobs are prioritized and completed within agreed timeframes. Takes immediate action on health and safety concerns and is available to respond to emergencies. Serves as the first point of contact for property issues, assessing needs and coordinating resolution before escalation to specialist vendors."}:p)}
try{if(localStorage.getItem(key+'-don-responsibilities-v1')!=='applied'){roster=updateDonResponsibilities(roster);localStorage.setItem(key,JSON.stringify(roster));localStorage.setItem(key+'-don-responsibilities-v1','applied')}}catch{roster=updateDonResponsibilities(roster)}
function updateLeadershipTitles(items){return items.map(p=>p.id==='justine'?{...p,role:'General Manager & Director of Guest Experience'}:p.id==='don'?{...p,role:'Director of Property Operations'}:p.id==='robin'?{...p,role:'Accountant'}:p.id==='laurence'?{...p,notes:p.notes.replace(/Serves Long Beach Island and Southern Ocean County\.?/gi,'').trim()}:p)}
try{if(localStorage.getItem(key+'-leadership-titles-v1')!=='applied'){roster=updateLeadershipTitles(roster);localStorage.setItem(key,JSON.stringify(roster));localStorage.setItem(key+'-leadership-titles-v1','applied')}}catch{roster=updateLeadershipTitles(roster)}
function status(t){$('#status').textContent=t;$('#status').style.display='block';setTimeout(()=>$('#status').style.display='none',4500)}function save(){try{localStorage.setItem(key,JSON.stringify(roster));status('Saved in this browser. Export a backup for handoff.')}catch{status('Browser storage unavailable. Export your roster to preserve changes.')}render()}function displayNotes(p){if(['owner','family'].includes(p.group))return '';if(p.id==='jeannie')return '';if(['rami','ramipartner'].includes(p.id))return '';return p.notes.replace(/Surname is provisional\.?/gi,'').replace(/(?:Last name|Name|Contact details|Service contact|Last name and contact details|Last name and specific responsibilities|Name and specific responsibilities) (?:to be confirmed|to be added)\.?/gi,'').replace(/Shoulder-season support\.?/gi,'').trim()}
function card(p,namesOnly=false){const b=document.createElement('button');b.className='card';b.setAttribute('aria-label','View or edit '+p.name);b.title='Open contact details';const role=p.id==='richard'?'Owner':['owner','family'].includes(p.group)?'':['jeannie','rami','ramipartner'].includes(p.id)?'':p.role;for(const [tag,cls,text] of [['h3','',p.name],['p','role',namesOnly?'':role],['p','notes',namesOnly?'':displayNotes(p)],['div','contact',namesOnly?'':p.email]]){if(text){const el=document.createElement(tag);el.className=cls;el.textContent=text;b.append(el)}}b.onclick=()=>edit(p.id);return b}
function render(){
const visibleRoster=seasonRoster().filter(p=>activeView!=='winter'||p.id!=='mike').map(p=>p.id==='michael'&&activeView==='winter'?{...p,role:'Snow Removal'}:p.id==='michael'&&activeView==='directory'?{...p,role:'Landscaping / Snow Removal'}:p);for(const id of ['owner-title','family-title']){const section=$('#'+id).closest('section');section.hidden=id==='family-title';if(section.nextElementSibling?.classList.contains('connector'))section.nextElementSibling.hidden=id==='family-title';}
['owner','family','leadership','support'].forEach(g=>$('#'+g).replaceChildren());
visibleRoster.filter(p=>p.group==='owner').forEach(p=>$('#owner').append(card(p)));
const oldSection=$('#team-title').closest('section');oldSection.hidden=true;oldSection.previousElementSibling.hidden=true;
const leaders=visibleRoster.filter(p=>p.group==='leadership');
const workers=visibleRoster.filter(p=>['support','justineTeam'].includes(p.group));
for(const leader of leaders){const column=document.createElement('div');column.className='leader-column';column.append(card(leader));
const assigned=workers.filter(p=>leader.id==='don'?(p.reports==='Don Blahut'||p.id==='sharon'):leader.id==='justine'?(p.reports!=='Don Blahut'):false);
if(leader.id!=='justine'&&assigned.length){const branch=document.createElement('section');branch.className='branch operational-team';branch.setAttribute('aria-label','Team reporting to '+leader.name);for(const person of assigned.filter(p=>p.id!=='mike')){const unit=document.createElement('div');unit.className='team-unit';unit.append(card(person));if(person.id==='jim'){const crew=visibleRoster.filter(p=>p.group==='jimTeam');if(crew.length){const nested=document.createElement('section');nested.className='branch jimTeam';nested.setAttribute('aria-label','Jim Blahut’s team');crew.forEach(p=>nested.append(card(p)));unit.append(nested)}}branch.append(unit)}column.append(branch);const mike=assigned.find(p=>p.id==='mike');if(mike){const backup=document.createElement('section');backup.className='emergency-backup don-backup';const label=document.createElement('h4');label.textContent='Emergency Backup';backup.append(label,card(mike));column.append(backup)}}
if(leader.id==='justine'){
const categories=[['Cleaning',['colleen','kristina','natalia']],['Chefs',['betsy','kristina']],['Server',activeView==='summer'?['natalia']:activeView==='shoulder'?['colleen']:activeView==='winter'?['betsy']:['colleen','natalia','betsy']],['On-Site Host',['jeannie','rami','ramipartner']]].filter(([title])=>activeView!=='summer'||title!=='On-Site Host');
const grid=document.createElement('div');grid.className='category-branches'+(activeView==='summer'?' summer-branches':'');
for(const [title,ids] of categories){const branch=document.createElement('section');branch.className='branch category-branch'+(title==='Champion'?' champions':'');branch.setAttribute('aria-label',title+' under Justine');const label=document.createElement('h3');label.className='category-title';label.textContent=title;branch.append(label);const people=visibleRoster.filter(p=>ids.includes(p.id));people.forEach(p=>branch.append(card(p,['Cleaning','Chefs','Server'].includes(title))));if(title==='Cleaning'){const backups=visibleRoster.filter(p=>['heather','amancia'].includes(p.id));if(backups.length){const backup=document.createElement('section');backup.className='emergency-backup';const heading=document.createElement('h4');heading.textContent='Emergency Backup';backup.append(heading);backups.forEach(p=>backup.append(card(p,true)));branch.append(backup)}}if(title==='Chefs'){const flavia=visibleRoster.find(p=>p.id==='flavia');if(flavia){const catering=document.createElement('section');catering.className='emergency-backup catering';const heading=document.createElement('h4');heading.textContent='Catering';catering.append(heading,card(flavia,true));branch.append(catering)}}if(title==='Chefs'&&activeView==='summer'){const backup=document.createElement('section');backup.className='emergency-backup';const heading=document.createElement('h4');heading.textContent='2x/week relief';backup.append(heading);const betsy=roster.find(p=>p.id==='betsy');if(betsy)backup.append(card(betsy,true));branch.append(backup)}if(title==='On-Site Host'&&(activeView==='shoulder'||activeView==='directory')){const backupPerson=visibleRoster.find(p=>p.id==='host-backup');if(backupPerson){const backup=document.createElement('section');backup.className='emergency-backup';const heading=document.createElement('h4');heading.textContent='Emergency Backup';const hostCard=card(backupPerson,true);backup.append(heading,hostCard);branch.append(backup)}}if(title==='On-Site Host'&&(activeView==='shoulder'||activeView==='directory')){const justine=roster.find(p=>p.id==='justine');if(justine){let backup=branch.querySelector('.emergency-backup:not(.catering)');if(!backup){backup=document.createElement('section');backup.className='emergency-backup';const heading=document.createElement('h4');heading.textContent='Emergency Backup';backup.append(heading);branch.append(backup)}const backupCard=card(justine,true);backup.append(backupCard)}}if(!people.length){const empty=document.createElement('p');empty.className='category-empty';empty.textContent='No contact assigned for this season.';branch.append(empty)}grid.append(branch)}column.append(grid);
const champions=activeView==='summer'?[]:visibleRoster.filter(p=>p.group==='champions');if(champions.length){const branch=document.createElement('section');branch.className='branch champions personal-branch';const title=document.createElement('h3');title.className='category-title';title.textContent='Champion';branch.append(title);champions.forEach(p=>branch.append(card(p)));column.append(branch)}
const categorized=new Set([...categories.flatMap(x=>x[1]),'heather','amancia','christine','sharon','host-backup','flavia']);const other=assigned.filter(p=>!categorized.has(p.id));if(other.length){const details=document.createElement('details');details.className='other-contacts';const summary=document.createElement('summary');summary.textContent='Other service contacts';details.append(summary);other.forEach(p=>details.append(card(p.id==='robin'?p:{...p,email:''})));column.append(details)}
}$('#leadership').append(column)}
const order=['jan','greg','ken','mike'];visibleRoster.filter(p=>p.group==='family').sort((a,b)=>{const x=order.indexOf(a.id),y=order.indexOf(b.id);return (x<0?99:x)-(y<0?99:y)}).forEach(p=>$('#family').append(card(p)))}

function edit(id){editing=id;const p=roster.find(p=>p.id===id)||{name:'',role:'',group:'support',relation:'',notes:'',reports:'',phone:'',email:''};$('#dialog-title').textContent=id?'Person details':'Add a person';for(const k of Object.keys(p)){const field=$('#person-form').elements.namedItem(k);if(field)field.value=p[k]}$('#remove').hidden=!id;$('#editor').showModal()}$('#close').onclick=()=>$('#editor').close();$('#add').onclick=()=>edit(null);$('#person-form').onsubmit=e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.target));for(const k in p)p[k]=p[k].trim();if(!p.name||!p.role)return;p.id=editing||'person-'+Date.now()+'-'+Math.random().toString(16).slice(2);if(editing)roster=roster.map(x=>x.id===editing?p:x);else roster.push(p);save();$('#editor').close()};$('#remove').onclick=()=>{const p=roster.find(p=>p.id===editing);if(p&&confirm('Remove '+p.name+' from this roster?')){roster=roster.filter(x=>x.id!==editing);save();$('#editor').close()}};$('#print').onclick=()=>window.print();$('#export').onclick=()=>{const blob=new Blob([JSON.stringify({title:'Williams Cottage Inn — Empire Edition',exportedAt:new Date().toISOString(),people:roster},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='williams-cottage-empire-roster.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};$('#import').onclick=()=>$('#file').click();$('#file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2000000)throw Error();const data=JSON.parse(await file.text());if(!valid(data.people))throw Error();if(confirm('Replace the roster in this browser with '+data.people.length+' imported entries?')){roster=data.people;save()}}catch{status('Please select a valid Williams Cottage roster export.')}e.target.value=''};updateView();
